language: node_js
node_js:
- 8.9.4
install: yarn
script: yarn build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "justinwhall.com"
  skip_cleanup: true
  acl: public_read
  local_dir: public